services:
  postgres_test:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend_test:
    build:
      context: ./backend
      target: development
      args:
        NODE_VERSION: ${NODE_VERSION}
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./backend:/app
      - backend_test_node_modules:/app/node_modules
    depends_on:
      postgres_test:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_test:5432/${POSTGRES_DB}?schema=public"
    env_file:
      - ./backend/.env.test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/auth/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  frontend_test:
    build:
      context: ./frontend
      target: development
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ./frontend:/app
      - frontend_test_node_modules:/app/node_modules
    env_file:
      - ./frontend/.env.test
    depends_on:
      backend_test:
        condition: service_healthy

  nginx-test:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend_test:
        condition: service_healthy
      frontend_test:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  cypress:
    image: cypress/included:cypress-15.10.0-node-24.13.1-chrome-144.0.7559.132-1-ff-147.0.3-edge-144.0.3719.115-1
    entrypoint:
      [
        "sh",
        "-c",
        "npm ci && npx cypress run --spec ${CYPRESS_SPEC:-cypress/e2e/**/*.cy.ts}",
      ]
    depends_on:
      nginx-test:
        condition: service_healthy
      frontend_test:
        condition: service_started
      backend_test:
        condition: service_healthy
    environment:
      CYPRESS_BASE_URL: http://nginx-test:80
    volumes:
      - ./frontend/cypress:/e2e/cypress
      - ./frontend/cypress.config.ts:/e2e/cypress.config.ts
      - ./frontend/package.json:/e2e/package.json
      - ./frontend/package-lock.json:/e2e/package-lock.json
      - ./frontend/src:/e2e/src
      - cypress_node_modules:/e2e/node_modules
    working_dir: /e2e

volumes:
  backend_test_node_modules:
  frontend_test_node_modules:
  cypress_node_modules:
