# Stage 1: Build
ARG NODE_VERSION=22.14.0
FROM node:${NODE_VERSION}-alpine AS build

WORKDIR /app

# для компиляции bcrypt
# RUN apk add --no-cache python3 make g++

COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY prisma.config.ts ./
COPY prisma/schema.prisma ./prisma/

RUN npm ci
RUN DATABASE_URL="postgresql://stub:stub@localhost:5432/stub" npx prisma generate

COPY . .
RUN npm run build

# Stage 2: Production
ARG NODE_VERSION=22.14.0
FROM node:${NODE_VERSION}-alpine AS production

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./

RUN npm ci --omit=dev

# RUN npm rebuild bcrypt --build-from-source

COPY --from=build /app/prisma ./prisma
COPY --from=build /app/prisma.config.ts ./
COPY --from=build /app/dist ./dist

EXPOSE 4200
CMD ["node", "dist/main.js"]