server {
    listen 80;
    server_name localhost nginx_test;

    location / {
        proxy_pass http://frontend_test:3000;
        proxy_set_header Host $host;
    }
    
    location /api/ {
        proxy_pass http://backend_test:4200/;
        proxy_set_header Host $host;
    }

    location /health {
        return 200 "healthy\n";
    }
}