name: Dev Branch CI
on:
  workflow_dispatch:
#   push:
#     branches: [dev]
#     paths-ignore:
#       - '**.md'
#       - 'docs/**'
jobs:
  cache-or-init:
    name: Cache or Install deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache fontend node_modules
        uses: actions/cache@v3
        id: cache-frontend
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}

      - name: Cache backend node_modules
        uses: actions/cache@v3
        id: cache-backend
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{  hashFiles('backend/package-lock.json')}}

      - name: Install frontend deps
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: npm ci

      - name: Install backend deps
        if: steps.cache-backend.outputs.cache-hit != 'true'
        working-directory: ./backend
        run: npm ci

      - name: Run Smoke Tests
        run: npm run test:e2e:smoke

      - name: Show container logs on failure
        if: failure()
        run: |
          docker logs backend_test
          docker logs frontend_test
          docker logs nginx_test

      - name: Clean Up
        if: always()
        run: npm run test:e2e:down
